---
title: "Principios SOLID"
subtitle: "Guía rápida"
description: "Descripción de los principos SOLID para software de calidad"
author: "Carlos Granell"
institute: "[GEOTEC](https://geotec.uji.es/), Universitat Jaume I"
date: last-modified
date-format: "MMM D, YYYY"
categories: [ei1026, solid-principles]

format: 
  revealjs:
    slide-number: true
    show-slide-number: all
    progress: true
    logo: ../../images/marca-uji-negre.png
    footer: "[https://cgranell.github.io/ei2639/](https://cgranell.github.io/ei2639/)"
    theme: [default]
    transition: fade
    preview-links: true
    author-meta: "Carlos Granell"
    date-meta: "15/09/2026"
    chalkboard: 
      theme: whiteboard
      buttons: false
      boardmarker-width: 3
from: markdown+emoji
execute:
  echo: true
bibliography: ../../references.bib
---


# Principios Básicos (OO) de Diseño de Software

::: incremental

-   [Encapsula lo que varía...](../01-course-content#encapsula)

-   [Programa a una interfaz, ...](../01-course-content#interfaz)

-   [Favorece la composición sobre ...](../01-course-content#composicion)

:::

# PERO

##  {data-menu-title="Aire de baja calidad" background-image="images/airquality.jpg" background-size="cover"}


:::notes
¿Cómo reconocemos que el aire es de baja calidad? ¿Que síntomas observamos? ¿Cómo lo percibimos?

Pollution collage element, torn paper design
Image credits: [Rawpixel.com](https://www.rawpixel.com/image/6792062/)
:::

##  {data-menu-title="Código de baja calidad" background-image="images/sw-code.jpg" background-size="cover"}


##  {data-menu-title="Código de baja calidad - síntomas" background-image="images/sw-code.jpg" background-size="cover"}

::: {.fragment .highlight-red .grow}
Dependencia
:::

::: {.fragment .highlight-red .grow}
Fragilidad
:::

::: {.fragment .highlight-red .grow}
Rigidez
:::

::: {.fragment .highlight-red .grow}
Falta de reutilización
:::

::: {.fragment .highlight-red .grow}
Viscosidad
:::


:::notes

¿Cómo reconocemos que un código es "malo"? 
¿Nos sirven los principios básicos de diseño de software para afirmarlo? 
¿Qué pasa cuando se modifica o actualiza un código malo? 

Síntomas del código malo: dependencia, fragilidad, rigidez, falta de reutilización o inmobilidad, viscosidad, etc.


Software developer programming code on black background
Image credits: [Rawpixel.com](https://www.rawpixel.com/image/593170)
:::

# SOLID

## Concepto 

**5 principios SOLID del diseño OO** para que el software sea más comprensible, flexible y fácil de mantener [@martin2002]

::: incremental
- **reducen la complejidad** de sistemas/aplicaciones a medida que crecen y

- **previenen** los síntomas del **código malo**
:::

:::notes

Receta contra los síntomas del código malo.

Principios SOLID introducidos por Robert Martin (*Uncle Bob*) en 2000: [Design Principles and Design Patterns](http://staff.cs.utu.fi/~jounsmed/doos_06/material/DesignPrinciplesAndPatterns.pdf)

[SOLID: The First 5 Principles of Object Oriented Design | DigitalOcean](https://www.digitalocean.com/community/conceptual-articles/s-o-l-i-d-the-first-five-principles-of-object-oriented-design)
:::


## Single Responsability Principle {#srp} 

Una clase debería tener:

. . .

{{< fa check >}} **un único propósito**: Reduce complejidad, fácil entender qué hace cada clase

. . .

{{< fa check >}} una **buena razón para cambiar**: Si hace demasiadas tareas, hay que modificarla cada vez que una tarea cambia.

. . .

{{< fa circle-arrow-right >}} [Principo de diseño encapsulación](../01-course-content#encapsula)

::: incremental
-   Tareas que cambian *por las mismas razones* en una clase

-   Tareas que cambian *por diferentes razones* en clases distintas
:::

:::notes
Reduce complejidad: Si una clase hace demasiadas cosas, hay que cambiarla cada vez que una de esas cosas cambia

Easier to understand: Classes, software components and microservices that have only one responsibility are much easier to explain, understand and implement than the ones that provide a solution for everything. This reduces the number of bugs, improves your development speed, and makes your life as a software developer a lot easier

[https://stackify.com/solid-design-principles/](https://stackify.com/solid-design-principles/)

:::

## Open/Closed Principle {#ocp}

. . .

{{< fa check >}} **Cerrada a la modificación**: Si una clase está desarrollada, probada y revisada, *no* la reescribas para añadir nuevas funcionalidades

. . .

{{< fa check >}} **Abierta a la extensión**: Si necesitas nuevo comportamiento, *crea subclases*

. . .

{{< fa circle-arrow-right >}} [Principo de diseño interfaz](../01-course-content#interfaz)

::: incremental
- Extender una clase permite añadir nuevo comportamiento sin descomponer clientes existentes de la clase original
:::

::: notes
Abierta y cerrada no son mutuamente excluyentes. 
Una clase puede estar al mismo tiempo abierta (para la extensión) y cerrada (para la modificación). 
El código simple es tanto abierto y cerrado.

Of course, the one exception to the rule is when fixing bugs in existing code.

[https://stackify.com/solid-design-open-closed-principle/](https://stackify.com/solid-design-open-closed-principle/)
:::


## Liskov Substitution Principle - Principio de sustitución de Liskov {#lsp}

{{< fa check >}} Si la clase A es un subtipo de la clase B, se podría reemplazar B por A sin alterar el comportamiento del sistema

. . .

{{< fa circle-arrow-right >}} Principio de diseño del sentido común

::: incremental
- Escribe abstracciones claras y bien definidas

- Subclases deben ser compatibles con (el comportamiento) de la clase padre

- Al sobrescribir un método, extiende el comportamiento base en lugar de sustituirlo por algo totalmente distinto
:::


::: notes
Escribe abstracciones nítidas, claras y bien definidas. 

[https://stackify.com/solid-design-liskov-substitution-principle/](https://stackify.com/solid-design-liskov-substitution-principle/)

:::

## Interface Segregation Principle {#isp}


{{< fa check >}} **Interfaces con funcionalidad/comportamiento conciso**: Evita interfaces para que los clientes (implementaciones) no dependan de métodos que no necesitan

. . .


{{< fa check >}} **Divide interfaces**: Si una interfaz es demasiado grande, sepárala en varias interfaces más pequeñas


:::notes
[https://stackify.com/interface-segregation-principle/](https://stackify.com/interface-segregation-principle/)
:::

## Dependency Inversion Principle {#dip}


{{< fa check >}} **Desacoplamiento** de módulos/componentes/clases: clases de alto nivel (componentes, servicios) no deben depender de clases de bajo nivel.

. . .

{{< fa circle-arrow-right >}} [Principo de diseño composición](../01-course-content#composicion)

:::incremental
- Componentes/entidades de alto nivel deben depender de abstracciones, no de implementaciones
:::

:::notes

Clases de bajo nivel implementan operaciones básicas como transferir datos por la red. 

Clases de alto nivel contienen la lógica de negocio que indican a las clases de bajo nivel que hagan algo.

El uso del operador `new` crea dependencias fuertes entre clases.


[https://stackify.com/dependency-inversion-principle/](https://stackify.com/dependency-inversion-principle/)
:::

## SOLID en ejemplos

- [@milington2022]: Ejemplos claros y sencillos en Java para entender los principios SOLID.

- [@oloruntoba2020] y [@soysal2022] proporcionan más ejemplos.

- [@martin2014]: Charla de Robert Martín (creador principios) in Yale


# Referencias {.scrollable}